service: auth-server

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  timeout: 30 # optional, in seconds, default is 6npm 

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: get-auth-url
          method: get

plugins:
  - serverless-offline